name: minber
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.4
  http: ^1.5.0
  hijri: ^3.0.0
  flutter_qiblah: ^3.1.0
  sensors_plus: ^6.1.2
  geolocator: ^13.0.4
  geocoding: ^2.2.0
  adhan_dart: ^1.0.9
  intl: ^0.20.2
  timezone: ^0.9.0
  flutter_timezone: ^4.1.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  device_info_plus: ^12.1.0
  # THIS IS CORRECT
  youtube_player_flutter: ^9.0.1
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^18.0.1
  video_player: ^2.10.0
  better_player_plus: ^1.1.2
  flutter_compass_v2: ^1.0.3
  permission_handler: ^12.0.1
  logger: ^2.6.2
  workmanager: ^0.9.0+3
  connectivity_plus: ^7.0.0
  provider: ^6.1.5+1
  chewie: ^1.13.0
  google_fonts: ^6.3.2
  pinput: ^5.0.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  package_info_plus: ^9.0.0
  pretty_http_logger: ^1.0.5
  flutter_vlc_player: ^7.4.4
  flutter_inappwebview: ^6.1.5
  flutter_markdown: ^0.7.7+1
  dio: ^5.3.3
  flutter_slidable: ^4.0.3
  audioplayers: ^6.5.1
  flutter_background_service: ^5.1.0
  android_alarm_manager_plus: ^5.0.0
  # video_player_avplay: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"
  # ✅ ADD THIS LINE - This adds the package to your project
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/web/hlsplayer.html
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21

# ✅ ADD THIS ENTIRE SECTION - This is your splash screen configuration
flutter_native_splash:
  # This creates a simple, blank, white splash screen.
  color: "#FFFFFF"
