// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvmkMHwwK3ISsIw8g4sQbewZ6YibxOvI0',
    appId: '1:712226370485:web:194b483d4d858c2b291ffc',
    messagingSenderId: '712226370485',
    projectId: 'minber-super-app-notifications',
    authDomain: 'minber-super-app-notifications.firebaseapp.com',
    storageBucket: 'minber-super-app-notifications.firebasestorage.app',
    measurementId: 'G-Q0KK2EY6W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9Ula0Eja4nviq6xU8cfpE85V7q49iTM',
    appId: '1:712226370485:android:c880a6fbf94e22ce291ffc',
    messagingSenderId: '712226370485',
    projectId: 'minber-super-app-notifications',
    storageBucket: 'minber-super-app-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzTdazCftdMc1JrggidrwdsnTC0Gq0NJQ',
    appId: '1:712226370485:ios:9d4de6bdf4576142291ffc',
    messagingSenderId: '712226370485',
    projectId: 'minber-super-app-notifications',
    storageBucket: 'minber-super-app-notifications.firebasestorage.app',
    iosBundleId: 'com.example.minberSuperAppNewFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzTdazCftdMc1JrggidrwdsnTC0Gq0NJQ',
    appId: '1:712226370485:ios:9d4de6bdf4576142291ffc',
    messagingSenderId: '712226370485',
    projectId: 'minber-super-app-notifications',
    storageBucket: 'minber-super-app-notifications.firebasestorage.app',
    iosBundleId: 'com.example.minberSuperAppNewFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvmkMHwwK3ISsIw8g4sQbewZ6YibxOvI0',
    appId: '1:712226370485:web:b13b099a97273db4291ffc',
    messagingSenderId: '712226370485',
    projectId: 'minber-super-app-notifications',
    authDomain: 'minber-super-app-notifications.firebaseapp.com',
    storageBucket: 'minber-super-app-notifications.firebasestorage.app',
    measurementId: 'G-37JR8FEFF5',
  );
}
